version: "3.9"
services:
  
  # DRS

  # Create DRS Database
  drs-database:
    image: ga4gh/ga4gh-starter-kit-utils:0.1.2
    container_name: part_1_drs_database
    volumes:
      - "./resources/drs/db:/db"
      - "./resources/drs/db-scripts:/db-scripts" 
    entrypoint: ["/bin/sh","-c"]
    command: 
      - |
        java -jar ga4gh-starter-kit-utils.jar database create-tables -d jdbc:sqlite:/db/drs.db /db-scripts/create-tables.sql
        java -jar ga4gh-starter-kit-utils.jar database add-test-dataset -d jdbc:sqlite:/db/drs.db /db-scripts/add-dev-dataset.sql
        
  # DRS Starter Kit
  drs:
    depends_on:
      - drs-database
    image: ga4gh/ga4gh-starter-kit-drs:0.3.1
    hostname: drs.starterkit.federatedgenomics.org
    container_name: part_1_drs
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - "./resources/drs/config:/config"
      - "./resources/drs/db:/db"
    command: -c /config/config.yml

  # WES

  # Create WES Database
  wes-database:
    image: ga4gh/ga4gh-starter-kit-utils:0.1.2
    container_name: part_1_wes_database
    volumes:
      - "./resources/wes/db:/db"
      - "./resources/wes/db-scripts:/db-scripts"
    entrypoint: ["/bin/sh","-c"]
    command: 
      - |
        java -jar ga4gh-starter-kit-utils.jar database create-tables -d jdbc:sqlite:/db/wes.db /db-scripts/create-tables.sql
        
  # WES Starter Kit
  wes:
    depends_on:
      - wes-database
    image: ga4gh/ga4gh-starter-kit-wes:0.3.2-nextflow
    hostname: wes.starterkit.federatedgenomics.org
    container_name: part_1_wes
    ports:
      - "6000:6000"
      - "6001:6001"
    volumes:
      - "./resources/wes/config:/config"
      - "./resources/wes/db:/db"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/shared/wes:/tmp/shared/wes"
    working_dir: /tmp/shared/wes
    command: -c /config/config.yml
    # required to communicate with services running on host 
    # (in our case, to communicate with drs container at `http://host.docker.internal:5000`) 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450