version: "3.9"
services:

  # Create DATA CONNECT Database
  data-connect-migrate:
    image: ga4gh/ga4gh-starter-kit-utils:0.1.2
    container_name: part_2_dataconnect_migrate
    volumes:
      - "./resources/data-connect/db:/db"
    command: database create-tables -d jdbc:sqlite:/db/data-connect.db data-connect@v0.1.1

  # Add default data to DATA CONNECT Database
  data-connect-dataset:
    depends_on:
      - data-connect-migrate
    image: ga4gh/ga4gh-starter-kit-utils:0.1.2
    container_name: part_2_dataconnect_dataset
    volumes:
      - "./resources/data-connect/db:/db"
      - "./resources/data-connect/db-scripts:/db-scripts"
    entrypoint: ["/bin/sh","-c"]
    command: 
      - |
        while [ ! -f /db/data-connect.db ]; do sleep 1; done
        java -jar ga4gh-starter-kit-utils.jar database add-test-dataset -d jdbc:sqlite:/db/data-connect.db /db-scripts/add-dev-dataset.sql

  # DATA CONNECT
  data-connect:
    depends_on:
      - data-connect-dataset
    image: ga4gh/ga4gh-starter-kit-data-connect:0.1.1
    container_name: part_2_dataconnect
    hostname: dataconnect.starterkit.ga4gh.org
    ports:
      - "4800:4500" # public
      - "4801:4501" # admin
    volumes:
      - "./resources/data-connect/config:/config"
      - "./resources/data-connect/db:/db"
    command: -c /config/config.yml

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450