version: "3.9"
services:

  # PASSPORT
  kratos-migrate:
    image: oryd/kratos:v0.9.0-alpha.2
    container_name: part_3_kratos_migrate
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure

  passport-ui-node:
    image: ga4gh/ga4gh-starter-kit-passport-ui-node:0.0.2
    container_name: part_3_passport_ui
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434/
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_BROWSER_URL=http://154.114.10.160:4433/
      - PASSPORT_BROKER_PUBLIC_URL=http://passport-broker.ga4gh.org:4500/ga4gh/passport/v1/
      - PASSPORT_BROKER_ADMIN_URL=http://passport-broker.ga4gh.org:4501/admin/ga4gh/passport/v1/
    ports:
      - "4455:4455"
    restart: unless-stopped

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.9.0-alpha.2
    container_name: part_3_kratos
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/kratos
        target: /etc/config/kratos
        
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    container_name: part_3_mailslurper
    ports:
      - "4436:4436"
      - "4437:4437"
      
  # Add default tables passport broker Database
  passport-broker-migrate:
    image: ga4gh/ga4gh-starter-kit-utils:0.1.2
    container_name: part_3_passport_broker_migrate
    volumes:
      - "./resources/passportBroker/db:/db"
      - "./resources/passportBroker/db-scripts:/db-scripts"
    # using local copy of create-tables.sql as the file name is different on passport-broker repo
    command: database create-tables -d jdbc:sqlite:/db/passport-broker.db /db-scripts/create-tables.sql

  # Add default data to passport broker Database
  passport-broker-dataset:
    depends_on:
      - passport-broker-migrate
    image: ga4gh/ga4gh-starter-kit-utils:0.1.2
    container_name: part_1_passport_broker_dataset
    volumes:
      - "./resources/passportBroker/db:/db"
      - "./resources/passportBroker/db-scripts:/db-scripts"
    # using local copy of add-test-dataset.sql as the file name is different on passport-broker repo
    command: database add-test-dataset -d jdbc:sqlite:/db/passport-broker.db /db-scripts/add-dev-dataset.sql

  passport-broker:
    image: ga4gh/ga4gh-starter-kit-passport-broker:0.0.2
    depends_on:
      - passport-broker-dataset
    container_name: part_3_passport_broker
    ports:
      - '4500:4500' # public
      - '4501:4501' # admin
    hostname: passport-broker.ga4gh.org
    volumes:
      - "./resources/passportBroker/db:/db"
      - "./resources/passportBroker/config:/config"
    command: -c /config/config.yml

  # DRS

  # Create DRS Database
  drs-migrate:
    image: ga4gh/ga4gh-starter-kit-utils:0.1.2
    container_name: part_3_drs_migrate
    volumes:
      - "./resources/drs/db:/db"
    command: database create-tables -d jdbc:sqlite:/db/drs.db drs@v0.3.1

  # Add default data to DRS Database
  drs-dataset:
    depends_on:
      - drs-migrate
    image: ga4gh/ga4gh-starter-kit-utils:0.1.2
    container_name: part_3_drs_dataset
    volumes:
      - "./resources/drs/db:/db"
    command: database add-test-dataset -d jdbc:sqlite:/db/drs.db drs@v0.3.1
    
  drs-dataset-add-visas:
    depends_on:
      - drs-migrate
      - drs-dataset
    image: ga4gh/ga4gh-starter-kit-utils:0.1.2
    container_name: part_3_drs_dataset_add_visas
    volumes:
      - "./resources/drs/db:/db"
      - "./resources/drs/db-scripts:/db-scripts"
    command: database add-test-dataset -d jdbc:sqlite:/db/drs.db /db-scripts/add-known-visas.sql

  # DRS Starter Kit
  drs:
    depends_on:
      - drs-migrate
      - drs-dataset
      - drs-dataset-add-visas
    image: ga4gh/ga4gh-starter-kit-drs:0.3.1
    container_name: part_3_drs
    hostname: drs.starterkit.federatedgenomics.org
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - "./resources/drs/config:/config"
      - "./resources/drs/db:/db"
    command: -c /config/config.yml

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
  
volumes:
  kratos-sqlite: