version: "3.9"
services:

  # PASSPORT
  kratos-migrate:
    image: oryd/kratos:v0.9.0-alpha.2
    container_name: part_3_kratos_migrate
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure

  passport-ui-node:
    image: ga4gh/ga4gh-starter-kit-passport-ui-node:0.0.2
    container_name: part_3_passport_ui
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434/
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_BROWSER_URL=http://154.114.10.160:4433/
      - PASSPORT_BROKER_PUBLIC_URL=http://passport-broker.ga4gh.org:4500/ga4gh/passport/v1/
      - PASSPORT_BROKER_ADMIN_URL=http://passport-broker.ga4gh.org:4501/admin/ga4gh/passport/v1/
    ports:
      - "4455:4455"
    restart: unless-stopped

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.9.0-alpha.2
    container_name: part_3_kratos
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/kratos
        target: /etc/config/kratos
        
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    container_name: part_3_mailslurper
    ports:
      - "4436:4436"
      - "4437:4437"
      
  # Create Passport Broker Database
  passport-broker-database:
    image: ga4gh/ga4gh-starter-kit-utils:0.1.2
    container_name: part_3_passport_broker_database
    volumes:
      - "./resources/passportBroker/db:/db"
      - "./resources/passportBroker/db-scripts:/db-scripts"
    entrypoint: ["/bin/sh","-c"]
    command: 
      - |
        java -jar ga4gh-starter-kit-utils.jar database create-tables -d jdbc:sqlite:/db/passport-broker.db /db-scripts/create-tables.sql
        java -jar ga4gh-starter-kit-utils.jar database add-test-dataset -d jdbc:sqlite:/db/passport-broker.db /db-scripts/add-dev-dataset.sql

  # Passport Broker Starter Kit
  passport-broker:
    image: ga4gh/ga4gh-starter-kit-passport-broker:0.0.2
    depends_on:
      - passport-broker-database
    container_name: part_3_passport_broker
    ports:
      - '4500:4500' # public
      - '4501:4501' # admin
    hostname: passport-broker.ga4gh.org
    volumes:
      - "./resources/passportBroker/db:/db"
      - "./resources/passportBroker/config:/config"
    command: -c /config/config.yml

  # DRS

  # Create DRS Database
  drs-database:
    image: ga4gh/ga4gh-starter-kit-utils:0.1.2
    container_name: part_3_drs_database
    volumes:
      - "./resources/drs/db:/db"
      - "./resources/drs/db-scripts:/db-scripts" 
    entrypoint: ["/bin/sh","-c"]
    command: 
      - |
        java -jar ga4gh-starter-kit-utils.jar database create-tables -d jdbc:sqlite:/db/drs.db /db-scripts/create-tables.sql
        java -jar ga4gh-starter-kit-utils.jar database add-test-dataset -d jdbc:sqlite:/db/drs.db /db-scripts/add-dev-dataset.sql
        java -jar ga4gh-starter-kit-utils.jar database add-test-dataset -d jdbc:sqlite:/db/drs.db /db-scripts/add-known-visas.sql

  # DRS Starter Kit
  drs:
    depends_on:
      - drs-database
    image: ga4gh/ga4gh-starter-kit-drs:0.3.1
    container_name: part_3_drs
    hostname: drs.starterkit.federatedgenomics.org
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - "./resources/drs/config:/config"
      - "./resources/drs/db:/db"
    command: -c /config/config.yml

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
  
volumes:
  kratos-sqlite: